# Generated by Django 4.1.3 on 2022-11-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
