# Generated by Django 4.1.3 on 2022-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='created_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
