# Generated by Django 4.1.3 on 2022-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0002_alter_clientmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='client_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
