# Generated by Django 4.1.3 on 2022-11-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0003_alter_clientmodel_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
