# Generated by Django 4.1.3 on 2022-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0004_clientmodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('p_created_at', models.CharField(blank=True, max_length=100)),
                ('p_created_by', models.CharField(blank=True, max_length=100)),
                ('users_assign', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projectUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=200)),
            ],
        ),
    ]
