# Generated by Django 4.1.3 on 2022-11-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0005_projectmodel_projectusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermodel',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectusermodel',
            name='projects',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
