# Generated by Django 4.1.3 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0006_projectusermodel_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermodel',
            name='record_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
