# Generated by Django 4.1.3 on 2022-11-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimap_app', '0007_projectusermodel_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermodel',
            name='created_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectusermodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectusermodel',
            name='user_assign_names',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
